version: "2"

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.14
    shm_size: 2g
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - selenium

  selenium-tests:
    image: ppms-analytics/selenium-tests
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - ../tests:/opt/tests/
    depends_on:
      - selenium
    networks:
      - selenium

  poligon:
    image: jzyinq/qa-honeypot
    shm_size: 2g
    ports:
      - 8282:80
    networks:
        selenium:
            ipv4_address: 10.243.5.2

networks:
  selenium:
    driver: bridge
    ipam:
      config:
        - subnet: 10.243.5.0/24
